name: RPi Image CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: PWD
      run: pwd
    - name: Build the RPi image
      run: cd lights-pi-gen && ./build-docker.sh
